apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
  namespace: aerfio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy: {}
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - image: ko://aerf.io/connect-go-fun/cmd/client
          imagePullPolicy: IfNotPresent
          name: client
          env:
            - name: APP_SERVER_URL
              value: "http://server:8080"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
