apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
  namespace: aerfio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  strategy: {}
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: ko://aerf.io/connect-go-fun/cmd/server
        imagePullPolicy: IfNotPresent
        name: server
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
  namespace: aerfio
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: grpc
  selector:
    app: server
